name       : rust
version    : 1.3.0
release    : 8
source     :
    - https://static.rust-lang.org/dist/rust-1.3.0-x86_64-unknown-linux-gnu.tar.gz : fa755b6331ff7554e6e8545ee20af7897b0adc65f471dd24ae8a467a944755b4
license    :
  - Apache 2.0
  - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
rundeps:
    - binutils
patterns : 
  - [/usr/bin/*, /usr/lib64/*, /usr/share/man/*, /usr/share/zsh/*, /etc]
  - docs : [/usr/share/doc/*]
install      : |
    install -d $installdir/usr/
    ./install.sh --prefix=$installdir/usr --components=cargo,rustc,rust-docs --libdir=$installdir/%libdir% --disable-ldconfig
    mv $installdir/usr/etc $installdir/
