name       : rust
version    : 1.0.0
release    : 3
source     :
    - https://static.rust-lang.org/dist/rustc-1.0.0-src.tar.gz : c304cbd4f7b25d116b73c249f66bdb5c9da8645855ce195a41bda5077b995eba
license    :
  - Apache 2.0
  - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
clang : no
builddeps  :
  - python
  - make
  - curl
  - g++
  - git
  - jemalloc-devel
setup      : |
    ./configure --prefix=/usr --enable-dist-host-only \
        --disable-docs --release-channel=stable \
        --host=x86_64-unknown-linux-gnu --target=x86_64-unknown-linux-gnu
build      : |
    %make
install    : |
    %make_install
