name       : rust
version    : 1.27.0
release    : 38
source     :
    - https://static.rust-lang.org/dist/rustc-1.27.0-src.tar.gz : 2cb9803f690349c9fd429564d909ddd4676c68dc48b670b8ddf797c2613e2d21
    - https://static.rust-lang.org/dist/2018-05-10/rustc-1.26.0-x86_64-unknown-linux-gnu.tar.gz : 7ca9a30010602aaf2244c376a3cc5baa89429d54da17b8ba1cb0cdfdc846cc61
    - https://static.rust-lang.org/dist/2018-05-10/rust-std-1.26.0-x86_64-unknown-linux-gnu.tar.gz : e27cb5c21541a500c8df919e15c8d3b002456ebbe573122e7b058cf5b4c3c13a
    - https://static.rust-lang.org/dist/2018-05-10/cargo-0.27.0-x86_64-unknown-linux-gnu.tar.gz : f50b64a7610401f4c1afe21de238663f33c621b7fc42c51401090ebd48e69fec
license    :
    - Apache-2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - python
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
setup      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    # See <rustsrc>/src/stage0.txt for the stage0 version and date the build system expects to find
    export STAGE0_DATE="2018-05-10"
    mkdir -p $workdir/build/cache/$STAGE0_DATE
    ln -sv $sources/rust{c,-std}-1.26.0-x86_64-unknown-linux-gnu.tar.gz \
        $sources/cargo-0.27.0-x86_64-unknown-linux-gnu.tar.gz \
        $workdir/build/cache/$STAGE0_DATE/
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    export PATH="$workdir/.bin:$PATH"
    sed -e 's:LIBDIR:%libdir%:' $pkgfiles/config.toml.in > $workdir/config.toml
build      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    export PATH="$workdir/.bin:$PATH"
    ./x.py build %JOBS%
    ./x.py doc %JOBS%
install    : |
    export PATH="$workdir/.bin:$PATH"
    export DESTDIR="$installdir"
    ./x.py install %JOBS%
