name       : rust
version    : 1.30.0
release    : 43
source     :
    - https://static.rust-lang.org/dist/rustc-1.30.0-src.tar.gz : cd0ba83fcca55b64c0c9f23130fe731dfc1882b73ae21bef96be8f2362c108ee
    - https://static.rust-lang.org/dist/2018-10-12/rustc-1.29.2-x86_64-unknown-linux-gnu.tar.gz : b04146b09edc4bad0de7c8fa1a5a2aa4416d365c03c5962b8a5b26c7047b7cc9
    - https://static.rust-lang.org/dist/2018-10-12/rust-std-1.29.2-x86_64-unknown-linux-gnu.tar.gz : 1fe9a0f354256483a354ee1b51c60bf9f3f48868581f7cb36d0cc51a82400605
    - https://static.rust-lang.org/dist/2018-10-12/cargo-0.30.0-x86_64-unknown-linux-gnu.tar.gz : 32f210fd3142fda7825a06e95d1aa4b54035c2da435d8cf0dd03fad410c8002f
license    :
    - Apache-2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - python
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
setup      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    # See <rustsrc>/src/stage0.txt for the stage0 version and date the build system expects to find
    export STAGE0_DATE="2018-10-12"
    mkdir -p $workdir/build/cache/$STAGE0_DATE
    ln -sv $sources/rust{c,-std}-1.29.2-x86_64-unknown-linux-gnu.tar.gz \
        $sources/cargo-0.30.0-x86_64-unknown-linux-gnu.tar.gz \
        $workdir/build/cache/$STAGE0_DATE/
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    export PATH="$workdir/.bin:$PATH"
    sed -e 's:LIBDIR:%libdir%:' $pkgfiles/config.toml.in > $workdir/config.toml
build      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    export PATH="$workdir/.bin:$PATH"
    ./x.py build %JOBS%
    ./x.py doc %JOBS%
install    : |
    export PATH="$workdir/.bin:$PATH"
    export DESTDIR="$installdir"
    ./x.py install %JOBS%
