name       : rust
version    : 1.28.0
release    : 40
source     :
    - https://static.rust-lang.org/dist/rustc-1.28.0-src.tar.gz : 1d5a81729c6f23a0a23b584dd249e35abe9c6f7569cee967cc42b1758ecd6486
    - https://static.rust-lang.org/dist/2018-07-20/rustc-1.27.2-x86_64-unknown-linux-gnu.tar.gz : ec3efc17ddbe6625840957049e15ebae960f447c8e8feb7da40c28dd6adf655f
    - https://static.rust-lang.org/dist/2018-07-20/rust-std-1.27.2-x86_64-unknown-linux-gnu.tar.gz : 68984f2233853d3e9c7c56edd72a91b5822157f28fdb42023fb311af68f842dd
    - https://static.rust-lang.org/dist/2018-07-20/cargo-0.28.0-x86_64-unknown-linux-gnu.tar.gz : 35da884d43a8620534f6da1fbdd05f1e1f24823749f93d3d3be0eb46b3a6d884
license    :
    - Apache-2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - python
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
setup      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    # See <rustsrc>/src/stage0.txt for the stage0 version and date the build system expects to find
    export STAGE0_DATE="2018-07-20"
    mkdir -p $workdir/build/cache/$STAGE0_DATE
    ln -sv $sources/rust{c,-std}-1.27.2-x86_64-unknown-linux-gnu.tar.gz \
        $sources/cargo-0.28.0-x86_64-unknown-linux-gnu.tar.gz \
        $workdir/build/cache/$STAGE0_DATE/
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    export PATH="$workdir/.bin:$PATH"
    sed -e 's:LIBDIR:%libdir%:' $pkgfiles/config.toml.in > $workdir/config.toml
build      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    export PATH="$workdir/.bin:$PATH"
    ./x.py build %JOBS%
    ./x.py doc %JOBS%
install    : |
    export PATH="$workdir/.bin:$PATH"
    export DESTDIR="$installdir"
    ./x.py install %JOBS%
