name       : rust
version    : 1.12.1
release    : 24
source     :
    - https://static.rust-lang.org/dist/rustc-1.12.1-src.tar.gz : 97913ae4cb255618aaacd1a534b11f343634b040b32656250d09d8d9ec02d3dc
license    :
    - Apache 2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - llvm-devel
    - clang
    - rust
    - cargo
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
setup      : |
    export CFLAGS="$CFLAGS -Wno-misleading-indentation -Wno-error=misleading-indentation"
    ./configure --prefix=/usr \
                --libdir=%libdir% \
                --sysconfdir=/etc \
                --datadir=/usr/share \
                --llvm-root=/usr \
                --release-channel=stable
                
build      : |
    export CFLAGS="$CFLAGS -Wno-misleading-indentation -Wno-error=misleading-indentation"
    %make
install    : |
    %make_install
