name       : rust
version    : 1.10.0
release    : 19
source     :
    - https://static.rust-lang.org/dist/rustc-1.10.0-src.tar.gz : a4015aacf4f6d8a8239253c4da46e7abaa8584f8214d1828d2ff0a8f56176869
license    :
    - Apache 2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - llvm-devel
    - clang
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
setup      : |
    export CFLAGS="$CFLAGS -Wno-misleading-indentation -Wno-error=misleading-indentation"
    ./configure --prefix=/usr \
                --libdir=%libdir% \
                --sysconfdir=/etc \
                --datadir=/usr/share \
                --llvm-root=/usr
                
build      : |
    export CFLAGS="$CFLAGS -Wno-misleading-indentation -Wno-error=misleading-indentation"
    %make
install    : |
    %make_install
