name       : rust
version    : 1.44.0
release    : 64
source     :
    - https://static.rust-lang.org/dist/rustc-1.44.0-src.tar.xz : b32fa7d6bd6ff9286aab2aa7ca696d1da921614cefc10f617aef68d9bce9118a
license    :
    - Apache-2.0
    - MIT
summary    :
    - A fast and secure system programming language
    - ^cargo : The Rust build system
description:
    - Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
    - ^cargo : The Rust build system.
component  :
    - programming
    - ^cargo : programming.tools
patterns   :
    - ^cargo :
        - /usr/bin/cargo
        - /usr/share/bash-completion/completions/cargo
        - /usr/share/man/man1/cargo*
        - /usr/share/zsh/site-functions/_cargo
libsplit   : no
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - cargo
    - fakeroot-32bit    # Tests
    - glibc-32bit-devel
    - libgcc-32bit
    - llvm-devel
rundeps    :
    - ^cargo :
        - libgit2
        - libssh2
        - rust
setup      : |
    %patch -p1 < $pkgfiles/Set-correct-libdir-in-bootstrap.patch
    sed -e 's|PREFIX|%PREFIX%|g' \
        -e 's|LIBDIR|%libdir%|g' $pkgfiles/config.toml.in > config.toml
build      : |
    # Don't use system libgit2 for now: https://github.com/rust-lang/rust/issues/63476
    #export LIBGIT2_SYS_USE_PKG_CONFIG=1
    export LIBSSH2_SYS_USE_PKG_CONFIG=1

    python3 x.py build
install    : |
    export DESTDIR=$installdir
    python3 x.py install
    install -dm00644 $installdir/usr/share/bash-completion/completions
    mv $installdir/etc/bash_completion.d/cargo $installdir/usr/share/bash-completion/completions/
    rm -rf $installdir/etc

    # Remove text files from libs (manifests, installation logs...)
    find $installdir/%libdir%/rustlib -maxdepth 1 -type f -delete

    # Remove license files and such
    rm -rf $installdir/usr/share/doc
check      : |
    # Some tests require targets we don't support, such as ARM.
    # For this reason we run only a small subset of the test suite.
    ./x.py test src/test/compile-fail || :
    ./x.py test src/test/pretty || :
    ./x.py test src/test/run-fail || :
    ./x.py test src/test/run-make || :
