name       : rust
version    : 1.32.0
release    : 47
source     :
    - https://static.rust-lang.org/dist/rustc-1.32.0-src.tar.gz : 4c594c7712a0e7e8eae6526c464bf6ea1d82f77b4f61717c3fc28fb27ba2224a
    - https://static.rust-lang.org/dist/2018-12-20/rustc-1.31.1-x86_64-unknown-linux-gnu.tar.gz : 77d47ce7e27a146e4301f11befd43f3fc5ac195ace0dfc07ac8154f130b057ea
    - https://static.rust-lang.org/dist/2018-12-20/rust-std-1.31.1-x86_64-unknown-linux-gnu.tar.gz : 699664b3a64959a2d75e486e19e7cc9934cbcbf2c57a977dd2a2b33cff367da1
    - https://static.rust-lang.org/dist/2018-12-20/cargo-0.32.0-x86_64-unknown-linux-gnu.tar.gz : b3d3dc57182fb173ecf367f7884dceb855a096d9b9b32eba994e3359ddc68cd4
license    :
    - Apache-2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - python
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
environment: |
    unset LD_AS_NEEDED LDFLAGS CXXFLAGS CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"
    export PATH="$workdir/.bin:$PATH"

    # You need to change this with every update
    export STAGE0_DATE="2018-12-20"
    export RUST_STD_VERS="1.33.1"
    export CARGO_VERS="0.32.0"
setup      : |
    mkdir -p $workdir/build/cache/$STAGE0_DATE
    ln -sv $sources/rust{c,-std}-$RUST_STD_VERS-x86_64-unknown-linux-gnu.tar.gz \
        $sources/cargo-$CARGO_VERS-x86_64-unknown-linux-gnu.tar.gz \
        $workdir/build/cache/$STAGE0_DATE/
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    sed -e 's:LIBDIR:%libdir%:' $pkgfiles/config.toml.in > $workdir/config.toml
build      : |
    ./x.py build %JOBS%
    ./x.py doc %JOBS%
install    : |
    export DESTDIR="$installdir"
    ./x.py install %JOBS%
check      : |
    ./x.py test src/test/compile-fail
    ./x.py test src/test/rustdoc
    ./x.py test src/test/run-fail
    ./x.py test src/test/run-pass
