name       : rust
version    : 1.7.0
release    : 15
source     :
    - https://static.rust-lang.org/dist/rust-1.7.0-x86_64-unknown-linux-gnu.tar.gz : d36634bd8df3d7565487b70af03dfda1c43c635cd6f2993f47cd61fda00d890a
license    :
  - Apache 2.0
  - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
rundeps:
    - binutils
    - glibc-devel
patterns : 
  - [/usr/bin/*, /usr/lib64/*, /usr/lib/*, /usr/share/man/*, /usr/share/zsh/*, /etc]
  - docs : [/usr/share/doc/*]
split : no
install      : |
    install -d $installdir/usr/
    ./install.sh --prefix=$installdir/usr --disable-ldconfig
    mv $installdir/usr/etc $installdir/
