name       : rust
version    : 1.69.0
release    : 106
source     :
    - https://static.rust-lang.org/dist/rustc-1.69.0-src.tar.xz : e533c903820b0c2ba10491b70105149d2243348f3b5e26bd7b6bdd022c7dbe75
license    :
    - Apache-2.0
    - MIT
summary    :
    - A fast and secure system programming language
    - ^cargo : The Rust build system
description:
    - Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
    - ^cargo : The Rust build system.
component  :
    - programming
    - ^cargo : programming.tools
patterns   :
    - ^cargo :
        - /usr/bin/cargo
        - /usr/libexec/cargo*
        - /usr/share/bash-completion/completions/cargo
        - /usr/share/man/man1/cargo*
        - /usr/share/zsh/site-functions/_cargo
libsplit   : no
networking : yes
builddeps  :
    # cargo
    - fakeroot-32bit    # Tests
    - glibc-32bit-devel
    - libgcc-32bit
    - llvm-devel
rundeps    :
    - ^cargo :
        - rust
setup      : |
    %patch -p1 < $pkgfiles/Set-correct-libdir-in-bootstrap.patch
    sed -e 's|PREFIX|%PREFIX%|g' \
        -e 's|LIBDIR|%libdir%|g' $pkgfiles/config.toml.in > config.toml
build      : |
    python3 x.py build --stage 2
install    : |
    DESTDIR=$installdir python3 x.py install
    install -Dm00644 $installdir/etc/bash_completion.d/* -t $installdir/usr/share/bash-completion/completions
    rm -rf $installdir/etc

    # Remove text files from libs (manifests, installation logs...)
    find $installdir/%libdir%/rustlib -maxdepth 1 -type f -delete

    # Remove license files and such
    rm -rf $installdir/usr/share/doc
check      : |
    # Some tests require targets we don't support, such as ARM.
    # For this reason we run only a small subset of the test suite.
    python3 x.py test --stage 2 src/test/compile-fail || :
    python3 x.py test --stage 2 src/test/pretty       || :
    python3 x.py test --stage 2 src/test/run-fail     || :
    python3 x.py test --stage 2 src/test/run-make     || :
