name       : rust
version    : 1.25.0
release    : 35
source     :
    - https://static.rust-lang.org/dist/rustc-1.25.0-src.tar.gz : eef63a0aeea5147930a366aee78cbde248bb6e5c6868801bdf34849152965d2d
    - https://static.rust-lang.org/dist/2018-02-15/rustc-1.24.0-x86_64-unknown-linux-gnu.tar.gz : 229fecc14e725d5dc2ce264925b362232649813cc436c51fab8ea376831f8d77
    - https://static.rust-lang.org/dist/2018-02-15/rust-std-1.24.0-x86_64-unknown-linux-gnu.tar.gz : 11f2a4fb8a7474e22dce61893b721dc54d9090bc7c784d17366a9a27541765ad
    - https://static.rust-lang.org/dist/2018-02-15/cargo-0.25.0-x86_64-unknown-linux-gnu.tar.gz : 1cbb2cb1be2838fd34d6e5becfcbcf0f14bdf1c917c2f9e0acb16eb3fc1e2e8a
license    :
    - Apache-2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - python
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
setup      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    # See <rustsrc>/src/stage0.txt for the stage0 version and date the build system expects to find
    export STAGE0_DATE="2018-02-15"
    mkdir -p $workdir/build/cache/$STAGE0_DATE
    ln -sv $sources/rust{c,-std}-1.24.0-x86_64-unknown-linux-gnu.tar.gz \
        $sources/cargo-0.25.0-x86_64-unknown-linux-gnu.tar.gz \
        $workdir/build/cache/$STAGE0_DATE/
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    export PATH="$workdir/.bin:$PATH"
    sed -e 's:LIBDIR:%libdir%:' $pkgfiles/config.toml.in > $workdir/config.toml
build      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    export PATH="$workdir/.bin:$PATH"
    ./x.py build %JOBS%
    ./x.py doc %JOBS%
install    : |
    export PATH="$workdir/.bin:$PATH"
    export DESTDIR="$installdir"
    ./x.py install %JOBS%
