name       : rust
version    : 1.10.0
release    : 18
source     :
    - https://static.rust-lang.org/dist/rust-1.10.0-x86_64-unknown-linux-gnu.tar.gz : f189303d52b37c8bb694b9d9739ae73ffa926cbdeffde1d5d6a5c6e811940293
license    :
    - Apache 2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
install    : |
    bashcompletion="$installdir/usr/share/bash-completion/completions"
    install -d $bashcompletion
    ./install.sh --prefix=$installdir/usr --disable-ldconfig
    mv $installdir/usr/etc/bash_completion.d/cargo $bashcompletion/
    rm -rf $installdir/usr/etc
