name       : rust
version    : 1.24.1
release    : 34
source     :
    - https://static.rust-lang.org/dist/rustc-1.24.1-src.tar.gz : 3ea53d45e8d2e9a41afb3340cf54b9745f845b552d802d607707cf04450761ef
    - https://static.rust-lang.org/dist/2018-01-04/rustc-1.23.0-x86_64-unknown-linux-gnu.tar.gz : 27b124fd0d94c082978ff81e45f7b7c37e91d64714587829bf828d64d76524ee
    - https://static.rust-lang.org/dist/2018-01-04/rust-std-1.23.0-x86_64-unknown-linux-gnu.tar.gz : 83c7351bdc4326caf785c208cff86682825dad4a89ccee705fa05f55ce7bd25b
    - https://static.rust-lang.org/dist/2018-01-04/cargo-0.24.0-x86_64-unknown-linux-gnu.tar.gz : ff8a454104aba20426ea898ed7515ec5da7de07d11733cdda17462455beb76e8
license    :
    - Apache-2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - python
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
setup      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    # See <rustsrc>/src/stage0.txt for the stage0 version and date the build system expects to find
    export STAGE0_DATE="2018-01-04"
    mkdir -p $workdir/build/cache/$STAGE0_DATE
    ln -sv $sources/rust{c,-std}-1.23.0-x86_64-unknown-linux-gnu.tar.gz \
        $sources/cargo-0.24.0-x86_64-unknown-linux-gnu.tar.gz \
        $workdir/build/cache/$STAGE0_DATE/
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    export PATH="$workdir/.bin:$PATH"
    sed -e 's:LIBDIR:%libdir%:' $pkgfiles/config.toml.in > $workdir/config.toml
build      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    export PATH="$workdir/.bin:$PATH"
    ./x.py build %JOBS%
    ./x.py doc %JOBS%
install    : |
    export PATH="$workdir/.bin:$PATH"
    export DESTDIR="$installdir"
    ./x.py install %JOBS%
