name       : rust
version    : 1.26.1
release    : 36
source     :
    - https://static.rust-lang.org/dist/rustc-1.26.1-src.tar.gz : 70a7961bd8ec43b2c01e9896e90b0a06804a7fbe0a5c05acc7fd6fed19500df0
    - https://static.rust-lang.org/dist/2018-03-29/rustc-1.25.0-x86_64-unknown-linux-gnu.tar.gz : f8f4ae2f4b76416bfa90758267df4280dd078235dfba92dac0431595493443be
    - https://static.rust-lang.org/dist/2018-03-29/rust-std-1.25.0-x86_64-unknown-linux-gnu.tar.gz : a3258308e3a9fe364d63b5d782efb285ab410bdfc01d168c119122ddbc9a02e2
    - https://static.rust-lang.org/dist/2018-03-29/cargo-0.26.0-x86_64-unknown-linux-gnu.tar.gz : 9ba227f2364f618dc9415dacf3a5dce17458e1cb9f6d4fe860416cb68db894e4
license    :
    - Apache-2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - python
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
setup      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    # See <rustsrc>/src/stage0.txt for the stage0 version and date the build system expects to find
    export STAGE0_DATE="2018-03-29"
    mkdir -p $workdir/build/cache/$STAGE0_DATE
    ln -sv $sources/rust{c,-std}-1.25.0-x86_64-unknown-linux-gnu.tar.gz \
        $sources/cargo-0.26.0-x86_64-unknown-linux-gnu.tar.gz \
        $workdir/build/cache/$STAGE0_DATE/
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    export PATH="$workdir/.bin:$PATH"
    sed -e 's:LIBDIR:%libdir%:' $pkgfiles/config.toml.in > $workdir/config.toml
build      : |
    unset LD_AS_NEEDED
    unset LDFLAGS
    unset CXXFLAGS
    unset CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    export PATH="$workdir/.bin:$PATH"
    ./x.py build %JOBS%
    ./x.py doc %JOBS%
install    : |
    export PATH="$workdir/.bin:$PATH"
    export DESTDIR="$installdir"
    ./x.py install %JOBS%
