name       : rust
version    : 1.17.0
release    : 29
source     :
    - https://static.rust-lang.org/dist/rustc-1.17.0-src.tar.gz : 4baba3895b75f2492df6ce5a28a916307ecd1c088dc1fd02dbfa8a8e86174f87
    - https://static.rust-lang.org/dist/rustc-1.16.0-x86_64-unknown-linux-gnu.tar.gz : b1dc3f754eeaf03891a3bd398c8c5024404c0078a334e5d8795e9dc419d147b3
    - https://static.rust-lang.org/dist/rust-std-1.16.0-x86_64-unknown-linux-gnu.tar.gz : cbd43de2ab819d3332ce309046f3b5d715c1b47877a237791b99c96b1fe0d555
    - https://s3.amazonaws.com/rust-lang-ci/cargo-builds/6b05583d71f982bcad049b9fa094c637c062e751/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz : d9e69d2b87dc0cf7fafe0e0eb64f82fe3414ef14fcb27f5eeff34df860e459d9
license    :
    - Apache 2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - python
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
setup      : |
    unset LD_AS_NEEDED

    # See <rustsrc>/src/stage0.txt for the rustc date and cargo revision the build system expects to find
    export STAGE0_RUSTC_DATE="2017-03-11"
    export STAGE0_CARGO_REVISION="6b05583d71f982bcad049b9fa094c637c062e751"
    mkdir -p $workdir/build/cache/{$STAGE0_RUSTC_DATE,$STAGE0_CARGO_REVISION}
    ln -sv $sources/rust{c,-std}-1.16.0-x86_64-unknown-linux-gnu.tar.gz $workdir/build/cache/$STAGE0_RUSTC_DATE/
    ln -sv $sources/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz $workdir/build/cache/$STAGE0_CARGO_REVISION/
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    export PATH="$PATH:$workdir/.bin"
    ./configure --prefix=/usr \
                --libdir=%libdir% \
                --sysconfdir=/etc \
                --datadir=/usr/share \
                --release-channel=stable \
                --enable-vendor
build      : |
    unset LD_AS_NEEDED
    export PATH="$PATH:$workdir/.bin"
    %make
install    : |
    export PATH="$PATH:$workdir/.bin"
    %make_install
