name       : rust
version    : 1.5.0
release    : 13
source     :
    - https://static.rust-lang.org/dist/rust-1.5.0-x86_64-unknown-linux-gnu.tar.gz : 60b83f74d882ce2ba5bc979b5b0589dca56659f215b3259e7188fed8c50aac9d
license    :
  - Apache 2.0
  - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
rundeps:
    - binutils
    - glibc-devel
patterns : 
  - [/usr/bin/*, /usr/lib64/*, /usr/lib/*, /usr/share/man/*, /usr/share/zsh/*, /etc]
  - docs : [/usr/share/doc/*]
split : no
install      : |
    install -d $installdir/usr/
    ./install.sh --prefix=$installdir/usr --disable-ldconfig
    mv $installdir/usr/etc $installdir/
