name       : rust
version    : 1.31.0
release    : 45
source     :
    - https://static.rust-lang.org/dist/rustc-1.31.0-src.tar.gz : 9ad54dc0baf1db5fc6a79d54e71c439c82aff85cd96778978456f2958211ef06
    - https://static.rust-lang.org/dist/2018-10-25/rustc-1.30.0-x86_64-unknown-linux-gnu.tar.gz : cc45058e9963d33ca28220e752d9e360b7e05f17e34284f5f8197738c3a88444
    - https://static.rust-lang.org/dist/2018-10-25/rust-std-1.30.0-x86_64-unknown-linux-gnu.tar.gz : 8514eedc0ed99ab75c61be3137c3e57c4115063ddc07aec842f687ebfc7ceda3
    - https://static.rust-lang.org/dist/2018-10-25/cargo-0.31.0-x86_64-unknown-linux-gnu.tar.gz : fe03acbd158d680bbdd8009b242b5ee49a7deab129345ce9c539d7c523c22db0
license    :
    - Apache-2.0
    - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
component  : programming
builddeps  :
    - python
rundeps    :
    - binutils
    - glibc-devel
patterns   :
    - [/usr/bin/*, /usr/lib/*, /usr/share/bash-completion/*, /usr/share/man/*]
    - docs : [/usr/share/doc/*]
libsplit   : no
environment: |
    unset LD_AS_NEEDED LDFLAGS CXXFLAGS CFLAGS

    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"
    export PATH="$workdir/.bin:$PATH"

    # You need to change this by every update
    export STAGE0_DATE="2018-10-25"
    export RUST_STD_VERS="1.30.0"
    export CARGO_VERS="0.31.0"
setup      : |
    mkdir -p $workdir/build/cache/$STAGE0_DATE
    ln -sv $sources/rust{c,-std}-$RUST_STD_VERS-x86_64-unknown-linux-gnu.tar.gz \
        $sources/cargo-$CARGO_VERS-x86_64-unknown-linux-gnu.tar.gz \
        $workdir/build/cache/$STAGE0_DATE/
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    sed -e 's:LIBDIR:%libdir%:' $pkgfiles/config.toml.in > $workdir/config.toml
build      : |
    ./x.py build %JOBS%
    ./x.py doc %JOBS%
install    : |
    export DESTDIR="$installdir"
    ./x.py install %JOBS%
check      : |
    ./x.py test src/test/compile-fail
    ./x.py test src/test/rustdoc
    ./x.py test src/test/run-fail
    ./x.py test src/test/run-pass