name       : rust
version    : 1.4.0
release    : 9
source     :
    - https://static.rust-lang.org/dist/rust-1.4.0-x86_64-unknown-linux-gnu.tar.gz : 2de2424b50ca2ab3a67c495b6af03c720801a2928ad30884438ad0f5436ac51d
license    :
  - Apache 2.0
  - MIT
summary    : Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
description: |
    Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
rundeps:
    - binutils
patterns : 
  - [/usr/bin/*, /usr/lib64/*, /usr/share/man/*, /usr/share/zsh/*, /etc]
  - docs : [/usr/share/doc/*]
install      : |
    install -d $installdir/usr/
    ./install.sh --prefix=$installdir/usr --components=cargo,rustc,rust-docs --libdir=$installdir/%libdir% --disable-ldconfig
    mv $installdir/usr/etc $installdir/
