name       : rust
version    : 1.37.0
release    : 54
source     :
    - https://static.rust-lang.org/dist/rustc-1.37.0-src.tar.xz : 10abffac50a729cf74cef6dd03193a2f4647541bd19ee9281be9e5b12ca8cdfd
    - https://packages.getsol.us/shannon/libg/libgit2/libgit2-0.26.7-24-1-x86_64.eopkg : 17a0ec0477a977e57de11dc0369b34ce3ed06c4f68a3443eda3a6e6d2bc0b432
license    :
    - Apache-2.0
    - MIT
summary    :
    - A fast and secure system programming language
    - docs : Documentation for the Rust language
    - ^cargo : The Rust build system
description:
    - Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.
    - docs : Documentation for the Rust language.
    - ^cargo : The Rust build system.
component  :
    - programming
    - docs : programming
    - ^cargo : programming.tools
patterns   :
    - ^cargo :
        - /usr/bin/cargo
        - /usr/share/bash-completion/completions/cargo
        - /usr/share/man/man1/cargo*
        - /usr/share/zsh/site-functions/_cargo
    - docs :
        - /usr/share/doc/*
libsplit   : no
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - cargo
    - fakeroot-32bit    # Tests
    - glibc-32bit-devel
    - libgcc-32bit
rundeps    :
    - ^cargo :
        - libgit2
        - libssh2
        - rust
environment: |
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$workdir/libgit2/install/usr/lib"
setup      : |
    uneopkg $sources/libgit2-0.26.7-24-1-x86_64.eopkg $workdir/libgit2
    %patch -p1 < $pkgfiles/Set-correct-libdir-in-bootstrap.patch
    %patch -p1 src/bootstrap/native.rs $pkgfiles/Fix-building-1.35.0-with-internal-llvm.patch
    sed -e 's|PREFIX|%PREFIX%|g' \
        -e 's|LIBDIR|%libdir%|g' $pkgfiles/config.toml.in > config.toml
build      : |
    export LIBGIT2_SYS_USE_PKG_CONFIG=1
    export LIBSSH2_SYS_USE_PKG_CONFIG=1

    # These env variables are for LLVM to be built correctly
    # since it sometimes fails on the build server
    unset LD_AS_NEEDED LDFLAGS CXXFLAGS CFLAGS
    export CFLAGS="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export CXXFLAGS="$CFLAGS"

    ./x.py build %JOBS%
    ./x.py doc %JOBS%
install    : |
    DESTDIR=$installdir ./x.py install %JOBS%
    install -m00644 -d $installdir/usr/share/bash-completion/completions
    mv $installdir/etc/bash_completion.d/cargo $installdir/usr/share/bash-completion/completions/
    rm -rf $installdir/etc

    # Remove text files from libs (manifests, installation logs...)
    find $installdir/%libdir%/rustlib -maxdepth 1 -type f -delete

    # Remove license files and such
    find $installdir/usr/share/doc/rust \( -name '*LICENSE*' -o -name '*COPYRIGHT*' \) -delete
    rm $installdir/usr/share/doc/rust/{README.md,README.md.old}
check      : |
    ./x.py test src/test/compile-fail
    ./x.py test src/test/run-fail
    ./x.py test src/test/run-pass
    ./x.py test src/test/rustdoc
